version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: 'mongo'
    ports:
      - '27017:27017'

  postgres:
    image: postgres
    restart: always
    container_name: 'pg'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./dbinit/postgres:/docker-entrypoint-initdb.d/:ro

  caddy:
    image: caddy:2.1.1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    network_mode: 'host'

volumes:
  caddy:
