version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: "mongo"
    ports:
      - "27017:27017"

  mongoadmin:
    restart: always
    image: mongo-express
    restart: always
    container_name: "mongoadmin"
    ports:
      - "8081:8081"