version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: 'mongo'

  postgres:
    image: postgres
    restart: always
    container_name: 'pg'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./dbinit/postgres:/docker-entrypoint-initdb.d/:ro

  caddy:
    image: caddy:2.1.1-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

  ui:
    build:
      context: ./ui
      args:
        - REACT_APP_ENDPOINT=${REACT_APP_ENDPOINT}
    restart: always

  server:
    build:
      context: ./server
    restart: always

volumes:
  caddy:
